[env:m5stick-s3]
platform = C:/Users/ccgg6/.platformio/platforms/espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM4
upload_speed = 115200
upload_flags =
  --before
  usb_reset
monitor_port = COM4
monitor_speed = 115200
platform_packages =
  framework-arduinoespressif32@file://C:/Users/ccgg6/.platformio/packages/framework-arduinoespressif32
  toolchain-xtensa-esp32s3@file://C:/Users/ccgg6/.platformio/packages/toolchain-xtensa-esp32s3
board_build.filesystem = littlefs
board_build.partitions = default.csv
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=1
lib_ldf_mode = deep+
lib_extra_dirs = lib
